<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('privacy_policy_sections', function (Blueprint $table) {
            $table->id();
            $table->string('slug')->unique();
            $table->string('title_ar');
            $table->string('title_en');
            $table->string('subtitle_ar', 500)->nullable();
            $table->string('subtitle_en', 500)->nullable();
            $table->longText('details_ar');
            $table->longText('details_en');
            $table->unsignedSmallInteger('sort_order')->default(0)->index();
            $table->boolean('is_active')->default(true)->index();
            $table->timestamps();
        });

        $now = now();

        DB::table('privacy_policy_sections')->insert([
            [
                'slug' => 'intro',
                'title_ar' => 'مقدمة ونطاق السياسة',
                'title_en' => 'Introduction and Scope',
                'subtitle_ar' => 'كيف تتعامل Right Choice مع بياناتك عند استخدام المنصة وخدماتها الرقمية.',
                'subtitle_en' => 'How Right Choice handles your data when you use the platform and its digital services.',
                'details_ar' => '<p>خصوصيتك مهمة لنا. تشرح هذه السياسة كيفية تعامل منصة Right Choice مع البيانات الشخصية عند استخدامك للموقع الإلكتروني أو الواجهات البرمجية أو أي خدمات رقمية مرتبطة به، ويشار إليها مجتمعة باسم «المنصة».</p><p>تغطي السياسة البيانات التي تقدمها لنا مباشرة، والبيانات الناتجة عن استخدامك للمنصة، والبيانات التي تصلنا من مزودي الخدمات عند الحاجة لتقديم وظائف مثل التحقق عبر الرسائل النصية أو الدفع الإلكتروني.</p><p>باستخدام المنصة أو إنشاء حساب أو إرسال بيانات من خلالها، فإنك تقر بأن بياناتك ستتم معالجتها وفقًا لهذه السياسة وبالقدر اللازم لتقديم الخدمات والوفاء بالالتزامات القانونية والتنظيمية المعمول بها.</p>',
                'details_en' => '<p>Your privacy matters to us. This policy explains how Right Choice handles personal data when you use our website, APIs, or any related digital services, collectively referred to as the Platform.</p><p>It covers data you provide directly, data generated through your use of the Platform, and data we receive from service providers when needed for functions such as SMS verification or electronic payments.</p><p>By using the Platform, creating an account, or submitting information through it, you acknowledge that your data may be processed in accordance with this policy to the extent required to provide services and comply with applicable legal and regulatory obligations.</p>',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'who-we-are',
                'title_ar' => 'من نحن',
                'title_en' => 'Who We Are',
                'subtitle_ar' => 'تعريف بمنصة Right Choice ووسائل التواصل الرسمية معنا.',
                'subtitle_en' => 'An introduction to Right Choice and our official contact channels.',
                'details_ar' => '<p>Right Choice منصة عقارية تعمل على تسهيل عرض العقارات والبحث عنها والتواصل بين أصحاب العقارات والمشترين أو المستأجرين والمطورين العقاريين، مع إتاحة خدمات إضافية مثل الباقات المدفوعة وتمييز الإعلانات.</p><ul><li>البريد الإلكتروني العام: <a href="mailto:info@rightchoice-co.com">info@rightchoice-co.com</a></li><li>البريد الإلكتروني للمبيعات: <a href="mailto:sales@rightchoice-co.com">sales@rightchoice-co.com</a></li><li>الهاتف: <a href="tel:0225196690">02-25196690</a></li><li>واتساب / موبايل: <a href="https://wa.me/201060660079" target="_blank" rel="noopener">01060660079</a></li><li>العنوان: محافظة القاهرة، المعادي، دجلة، شارع 216، عمارة 17، الدور الثاني، فيلا 1.</li></ul>',
                'details_en' => '<p>Right Choice is a real estate platform that helps property owners, buyers, tenants, and developers list, discover, and communicate about properties. The Platform also offers additional services such as paid packages and featured listings.</p><ul><li>General email: <a href="mailto:info@rightchoice-co.com">info@rightchoice-co.com</a></li><li>Sales email: <a href="mailto:sales@rightchoice-co.com">sales@rightchoice-co.com</a></li><li>Phone: <a href="tel:0225196690">02-25196690</a></li><li>WhatsApp / Mobile: <a href="https://wa.me/201060660079" target="_blank" rel="noopener">01060660079</a></li><li>Address: Building 17, Street 216, Degla, Maadi, Cairo, Egypt, second floor, Villa 1.</li></ul>',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'personal-data',
                'title_ar' => 'البيانات الشخصية',
                'title_en' => 'Personal Data',
                'subtitle_ar' => 'المقصود بالبيانات الشخصية التي تحدد هويتك بصورة مباشرة أو غير مباشرة.',
                'subtitle_en' => 'What personal data means and how it may identify you directly or indirectly.',
                'details_ar' => '<p>البيانات الشخصية هي أي معلومات تتعلق بشخص طبيعي محدد أو يمكن تحديد هويته بصورة مباشرة أو غير مباشرة، مثل الاسم ورقم الهاتف والبريد الإلكتروني وبيانات الحساب. أما البيانات التي يتم إخفاء هوية أصحابها بصورة لا تسمح بإعادة التعرف عليهم فلا تعامل عادةً كبيانات شخصية.</p>',
                'details_en' => '<p>Personal data means any information relating to an identified or identifiable natural person, directly or indirectly, such as a name, phone number, email address, or account information. Data that has been anonymized so that a person can no longer reasonably be identified is generally not treated as personal data.</p>',
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'data-we-collect',
                'title_ar' => 'البيانات التي نجمعها',
                'title_en' => 'Data We Collect',
                'subtitle_ar' => 'فئات البيانات التي قد نجمعها بحسب نوع الحساب والخدمات التي تستخدمها.',
                'subtitle_en' => 'Categories of data we may collect depending on your account type and the services you use.',
                'details_ar' => '<p>قد نجمع الفئات التالية بحسب نوع الحساب والوظائف التي تستخدمها:</p><ul><li><strong>بيانات الحساب والهوية:</strong> الاسم، البريد الإلكتروني، رقم الهاتف، كلمة المرور بصيغة آمنة، نوع الحساب، حالة الحساب، صورة الملف الشخصي وبيانات التحقق.</li><li><strong>بيانات المطور أو النشاط العقاري:</strong> اسم المطور أو الشركة، المسمى الوظيفي، السجل التجاري، البطاقة الضريبية، شعار الشركة أو صورة الحساب.</li><li><strong>بيانات التحقق والأمان:</strong> حالة التحقق من رقم الهاتف، رمز OTP لفترة تشغيلية، وبيانات المصادقة اللازمة لتأمين الجلسات والواجهات البرمجية.</li><li><strong>بيانات العقارات والإعلانات:</strong> العنوان والوصف والصور ونوع العرض والعقار والسعر والمساحات والغرف والحمامات والتمويل والتقسيط والإيجار والترخيص والمزايا.</li><li><strong>بيانات الموقع العقاري:</strong> المحافظة والمنطقة والحي أو الكمبوند، وقد تشمل إحداثيات خط العرض والطول للعقار.</li><li><strong>بيانات الاهتمام والتفاعل:</strong> المفضلة، العقارات التي طلبت التواصل بشأنها، وسيلة التواصل، واستخدام النقاط أو الباقات.</li><li><strong>بيانات الدفع والمعاملات:</strong> المبلغ والعملة وحالة وطريقة الدفع وأرقام المرجع والمعاملة وتاريخ السداد وبيانات الاسترداد ورسوم بوابة الدفع والردود الفنية.</li><li><strong>بيانات التواصل والدعم:</strong> الاسم والهاتف والبريد والموضوع ومحتوى الرسالة والشكاوى وطلبات الدعم أو حذف الحساب.</li><li><strong>بيانات تقنية وتشغيلية:</strong> بيانات الجلسة وتسجيل الدخول وعنوان IP وسجلات الخادم ونوع المتصفح والجهاز ونظام التشغيل والتوقيت واللغة.</li></ul><h3>بيانات لا نطلبها منك عادةً</h3><p>لا نطلب منك كجزء طبيعي من استخدام المنصة تقديم بيانات شديدة الحساسية مثل المعتقدات الدينية أو الآراء السياسية أو البيانات الصحية أو الوراثية أو تفاصيل الحياة الخاصة، وننصح بعدم إدراج هذه المعلومات داخل وصف العقار أو الشكاوى أو نماذج التواصل ما لم تكن ضرورية بشكل واضح ومسموح بها قانونًا.</p><h3>ماذا يحدث إذا لم تقدم البيانات المطلوبة؟</h3><p>يمكنك تصفح بعض أجزاء المنصة دون إنشاء حساب، ولكن بعض الخدمات تحتاج بيانات محددة. إذا لم تقدم البيانات اللازمة للتسجيل أو التحقق أو الدفع أو تنفيذ خدمة معينة فقد لا نتمكن من إتمام تلك الخدمة.</p>',
                'details_en' => '<p>Depending on your account type and the features you use, we may collect the following categories:</p><ul><li><strong>Account and identity data:</strong> name, email, phone number, securely stored password data, account type and status, profile image, and verification information.</li><li><strong>Developer or business data:</strong> developer or company name, job title, commercial registration, tax card, company logo, and account image.</li><li><strong>Verification and security data:</strong> phone verification status, temporary OTP data, and authentication information required to secure sessions and APIs.</li><li><strong>Property and listing data:</strong> title, description, images, listing type, property type, price, area, rooms, bathrooms, financing, installments, rent, licensing, and features.</li><li><strong>Property location data:</strong> governorate, area, neighborhood or compound, and property latitude and longitude when provided.</li><li><strong>Interest and interaction data:</strong> favorites, properties you contacted, communication method, points, and package usage.</li><li><strong>Payment and transaction data:</strong> amount, currency, payment status and method, reference numbers, payment date, refund details, gateway fees, and technical responses.</li><li><strong>Communication and support data:</strong> name, phone, email, subject, message content, complaints, support requests, and account deletion requests.</li><li><strong>Technical and operational data:</strong> session and login data, IP address, server logs, browser and device type, operating system, time, and language.</li></ul><h3>Data we do not normally request</h3><p>As part of normal Platform use, we do not ask for highly sensitive information such as religious beliefs, political opinions, health or genetic information, or intimate personal details. Please avoid including such information in property descriptions, complaints, or contact forms unless clearly necessary and legally permitted.</p><h3>If required data is not provided</h3><p>You can browse some parts of the Platform without an account, but certain services require specific information. If you do not provide data required for registration, verification, payment, or a particular service, we may be unable to provide that service.</p>',
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'sources',
                'title_ar' => 'مصادر البيانات',
                'title_en' => 'Data Sources',
                'subtitle_ar' => 'الطرق التي نحصل بها على بياناتك أثناء استخدامك للمنصة.',
                'subtitle_en' => 'How we obtain data while you use the Platform.',
                'details_ar' => '<ul><li>مباشرة منك عند التسجيل أو تحديث الحساب أو نشر إعلان أو رفع صور أو إرسال نموذج تواصل أو شكوى.</li><li>من استخدامك للمنصة، مثل إنشاء قائمة مفضلة أو طلب التواصل مع صاحب عقار أو الاشتراك في باقة.</li><li>من مزودي الخدمات الذين نتعامل معهم لتقديم وظيفة طلبتها، مثل مزود الرسائل النصية ومزود الدفع.</li><li>من السجلات التقنية الناتجة عن تشغيل الموقع والخوادم وأنظمة الأمان.</li></ul>',
                'details_en' => '<ul><li>Directly from you when you register, update your account, publish a listing, upload images, or submit a contact form or complaint.</li><li>From your use of the Platform, such as creating favorites, requesting contact with a property owner, or subscribing to a package.</li><li>From service providers used to deliver a function you requested, such as SMS and payment providers.</li><li>From technical records generated by the website, servers, and security systems.</li></ul>',
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'purposes',
                'title_ar' => 'استخدام البيانات',
                'title_en' => 'How We Use Data',
                'subtitle_ar' => 'الأغراض التي نستخدم من أجلها بياناتك لتشغيل الخدمات وحماية المنصة.',
                'subtitle_en' => 'Why we use your data to operate services and protect the Platform.',
                'details_ar' => '<ul><li><strong>إنشاء وإدارة الحساب:</strong> التسجيل والتحقق وإدارة حالة الحساب واستعادة الوصول وتأمين الجلسات.</li><li><strong>التحقق والأمان:</strong> إرسال OTP ومكافحة إساءة الاستخدام والاحتيال وحماية الحسابات والأنظمة.</li><li><strong>تشغيل الإعلانات العقارية:</strong> إنشاء الإعلانات ومراجعتها ونشرها وعرض بياناتها وصورها وموقعها وإدارة الإعلانات المميزة.</li><li><strong>التواصل بين المستخدمين:</strong> تمكين طلب التواصل مع أصحاب العقارات وتسجيل الاهتمام.</li><li><strong>الباقات والنقاط:</strong> إدارة الاشتراكات والنقاط وتمييز العقارات وتتبع صلاحية الباقات.</li><li><strong>الدفع والاسترداد:</strong> إرسال البيانات اللازمة لمزود الدفع والتحقق من حالة المعاملة ومعالجة المرتجعات والتسويات.</li><li><strong>الدعم والشكاوى:</strong> الرد على الاستفسارات ومعالجة الشكاوى ومتابعة المشكلات.</li><li><strong>تحسين التشغيل والأداء:</strong> تشخيص الأعطال وحماية المنصة وقياس الاستخدام وتحسين تجربة المستخدم.</li></ul><div class="rc-privacy-note">لن نستخدم بياناتك لغرض غير متوافق بصورة جوهرية مع الغرض الذي جمعت من أجله إلا إذا كان ذلك مسموحًا به قانونًا أو تم إخطارك أو الحصول على موافقتك عندما تكون الموافقة مطلوبة.</div>',
                'details_en' => '<ul><li><strong>Account creation and management:</strong> registration, verification, account status management, account recovery, and session security.</li><li><strong>Verification and security:</strong> sending OTP codes, preventing abuse and fraud, and protecting accounts and systems.</li><li><strong>Property listings:</strong> creating, reviewing, publishing, and displaying listings, images, locations, and featured ads.</li><li><strong>User communication:</strong> enabling contact requests with property owners and recording interest.</li><li><strong>Packages and points:</strong> managing subscriptions, points, featured listings, and package validity.</li><li><strong>Payments and refunds:</strong> sending required information to payment providers, checking transaction status, and processing refunds and settlements.</li><li><strong>Support and complaints:</strong> responding to inquiries, handling complaints, and following up on issues.</li><li><strong>Operations and performance:</strong> diagnosing errors, protecting the Platform, measuring usage, and improving user experience.</li></ul><div class="rc-privacy-note">We will not use your data for a purpose that is materially incompatible with the purpose for which it was collected unless legally permitted, you are notified, or your consent is obtained where required.</div>',
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'public-data',
                'title_ar' => 'البيانات التي تظهر للآخرين',
                'title_en' => 'Data Visible to Others',
                'subtitle_ar' => 'المعلومات التي قد تصبح عامة بحكم طبيعة الإعلانات العقارية.',
                'subtitle_en' => 'Information that may become public because of the nature of property listings.',
                'details_ar' => '<p>طبيعة المنصة العقارية تعني أن بعض المعلومات التي تختار نشرها تكون متاحة لمستخدمي الموقع أو لمحركات البحث، مثل بيانات الإعلان ووصف العقار وصوره وسعره وموقعه العام ونوع العرض.</p><p>قد تتاح بعض بيانات التواصل مع صاحب الإعلان للمستخدمين وفق آلية المنصة وصلاحيات الحساب أو النقاط أو الباقات. لذلك يجب ألا تنشر داخل الإعلان بيانات لا ترغب في إتاحتها للآخرين.</p>',
                'details_en' => '<p>Because Right Choice is a real estate Platform, some information you choose to publish may be visible to website users or search engines, including listing details, property description, images, price, general location, and offer type.</p><p>Some owner contact information may be made available according to Platform rules, account permissions, points, or packages. You should not include information in a listing that you do not want to make available to others.</p>',
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'sharing',
                'title_ar' => 'مشاركة البيانات',
                'title_en' => 'Data Sharing',
                'subtitle_ar' => 'الجهات التي قد نشارك معها البيانات عند الحاجة لتقديم الخدمة أو الالتزام بالقانون.',
                'subtitle_en' => 'Parties with whom data may be shared when needed to provide services or comply with law.',
                'details_ar' => '<ul><li>مزود الدفع الإلكتروني، بما في ذلك فوري، لمعالجة الدفع والتحقق والاسترداد والتسوية.</li><li>مزود خدمات الرسائل النصية لإرسال رموز التحقق OTP والرسائل التشغيلية.</li><li>مزودو الاستضافة والبنية التحتية والدعم الفني والأمن السيبراني والبريد الإلكتروني عند الحاجة.</li><li>خدمات الخرائط أو المحتوى الخارجي المضمن، مثل خرائط Google.</li><li>المستشارون والمراجعون والجهات المهنية عند الحاجة القانونية أو المحاسبية أو الأمنية.</li><li>الجهات الحكومية أو القضائية أو التنظيمية إذا كان الإفصاح مطلوبًا بموجب قانون أو أمر ملزم.</li><li>طرف يستحوذ على كل أو جزء من النشاط أو يندمج معه، مع استمرار الالتزامات القانونية المناسبة.</li></ul>',
                'details_en' => '<ul><li>Electronic payment providers, including Fawry, for payment processing, verification, refunds, and settlement.</li><li>SMS providers for OTP verification and operational messages.</li><li>Hosting, infrastructure, technical support, cybersecurity, and email providers when needed.</li><li>Map services or embedded external content, such as Google Maps.</li><li>Advisers, auditors, and professional service providers where legally, financially, or operationally required.</li><li>Government, judicial, or regulatory authorities when disclosure is required by law or a binding order.</li><li>A party acquiring or merging with all or part of the business, subject to appropriate legal obligations.</li></ul>',
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'payments',
                'title_ar' => 'الدفع وفوري',
                'title_en' => 'Payments and Fawry',
                'subtitle_ar' => 'كيفية معالجة بيانات المعاملات عند استخدام الدفع الإلكتروني عبر فوري.',
                'subtitle_en' => 'How transaction data is handled when electronic payment through Fawry is used.',
                'details_ar' => '<p>عند استخدام الدفع عبر فوري، قد نرسل إلى مزود الدفع البيانات اللازمة لإتمام العملية، مثل رقم تعريف العميل ورقم الهاتف والبريد الإلكتروني ومبلغ العملية والعملة ووصف الخدمة.</p><p>كما نحتفظ بسجلات تشغيلية مرتبطة بالمعاملة مثل رقم المرجع ورقم مرجع التاجر وحالة الدفع وتاريخ السداد وبيانات الاسترداد والردود الفنية ذات الصلة.</p><div class="rc-privacy-note">لا نهدف إلى تخزين رقم البطاقة البنكية الكامل أو رمز الأمان CVV داخل قواعد بيانات Right Choice. إذا كانت طريقة الدفع تتطلب بيانات مالية إضافية، فيجب إدخالها ومعالجتها وفق واجهة وشروط مزود الدفع المعتمد.</div>',
                'details_en' => '<p>When you pay through Fawry, we may send the payment provider information needed to complete the transaction, such as customer identifier, phone number, email address, amount, currency, and service description.</p><p>We also keep operational transaction records such as reference numbers, merchant reference, payment status, payment date, refund information, and relevant technical responses.</p><div class="rc-privacy-note">Right Choice does not intend to store full bank card numbers or CVV security codes in its databases. If a payment method requires additional financial data, that data should be entered and processed through the approved payment provider interface and under its terms.</div>',
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'cookies',
                'title_ar' => 'ملفات الارتباط',
                'title_en' => 'Cookies',
                'subtitle_ar' => 'استخدام الجلسات وملفات تعريف الارتباط والتقنيات التشغيلية المشابهة.',
                'subtitle_en' => 'Use of sessions, cookies, and similar operational technologies.',
                'details_ar' => '<p>تستخدم المنصة تقنيات تشغيلية مثل ملفات تعريف الارتباط أو الجلسات الرقمية للحفاظ على تسجيل الدخول، حماية الطلبات، حفظ بعض التفضيلات مثل اللغة، وتشغيل الوظائف الأساسية للموقع.</p><p>قد تستخدم الخدمات الخارجية المضمنة، مثل الخرائط أو بوابات الدفع، ملفات تعريف ارتباط أو تقنيات مشابهة وفق سياساتها الخاصة.</p>',
                'details_en' => '<p>The Platform uses operational technologies such as cookies and digital sessions to maintain login state, protect requests, store certain preferences such as language, and operate essential website functions.</p><p>Embedded external services, such as maps or payment gateways, may use cookies or similar technologies in accordance with their own policies.</p>',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'security',
                'title_ar' => 'أمن البيانات',
                'title_en' => 'Data Security',
                'subtitle_ar' => 'التدابير التي نتخذها لحماية البيانات والحسابات والأنظمة.',
                'subtitle_en' => 'Measures used to protect data, accounts, and systems.',
                'details_ar' => '<p>نتخذ تدابير تقنية وتنظيمية معقولة لحماية البيانات من الوصول غير المصرح به أو الفقد أو التعديل أو الإفصاح غير المشروع. وتشمل آليات المنصة بحسب الوظيفة المستخدمة تخزين كلمات المرور بصيغة تجزئة آمنة، التحقق من البريد أو الهاتف، رموز الوصول للواجهات البرمجية، المصادقة الثنائية عند تفعيلها، وإدارة الصلاحيات للمستخدمين الإداريين.</p><p>لا توجد وسيلة نقل أو تخزين إلكتروني يمكن ضمان أمانها بنسبة 100%، لذلك نراجع وسائل الحماية ونحدثها عند الحاجة.</p>',
                'details_en' => '<p>We use reasonable technical and organizational measures to protect data from unauthorized access, loss, alteration, or unlawful disclosure. Depending on the feature used, these measures include secure password hashing, email or phone verification, API access tokens, two-factor authentication when enabled, and permission controls for administrative users.</p><p>No electronic transmission or storage method can be guaranteed to be 100% secure, so we review and update our safeguards when appropriate.</p>',
                'sort_order' => 11,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'retention',
                'title_ar' => 'مدة الاحتفاظ',
                'title_en' => 'Data Retention',
                'subtitle_ar' => 'الفترة التي نحتفظ خلالها بالبيانات وفق احتياجات التشغيل والقانون.',
                'subtitle_en' => 'How long data is kept for operational and legal needs.',
                'details_ar' => '<p>نحتفظ بالبيانات فقط للمدة اللازمة لتقديم الخدمات وإدارة الحسابات والإعلانات والمعاملات ومعالجة النزاعات والشكاوى والوفاء بالمتطلبات المالية والقانونية وممارسة الحقوق أو الدفاع عنها.</p><p>قد يلزم الاحتفاظ بسجلات المعاملات والدفع والاسترداد وطلبات الدعم لفترة أطول من البيانات التشغيلية المؤقتة.</p>',
                'details_en' => '<p>We keep data only for as long as necessary to provide services, manage accounts, listings and transactions, handle disputes and complaints, meet financial and legal requirements, and establish or defend legal rights.</p><p>Transaction, payment, refund, and support records may need to be retained longer than temporary operational data.</p>',
                'sort_order' => 12,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'account-deletion',
                'title_ar' => 'حذف الحساب',
                'title_en' => 'Account Deletion',
                'subtitle_ar' => 'آلية طلب حذف الحساب وما يعنيه الحذف المنطقي للبيانات.',
                'subtitle_en' => 'How account deletion requests work and what soft deletion means.',
                'details_ar' => '<p>توفر المنصة آلية لطلب حذف الحساب. يتم إرسال الطلب إلى الإدارة لمراجعته، ويمكن قبوله أو رفضه وفق حالة الحساب والالتزامات المرتبطة به.</p><p>عند الموافقة على الطلب، قد يتم تعطيل الحساب باستخدام «الحذف المنطقي» (Soft Delete) بدلًا من الإزالة الفورية والنهائية لجميع السجلات. ويعني ذلك أن الحساب يتوقف عن الاستخدام العادي مع إمكان الاحتفاظ ببعض البيانات لأغراض الاستعادة أو السجلات المالية أو حماية الحقوق أو الالتزام بالقانون.</p>',
                'details_en' => '<p>The Platform provides a mechanism to request account deletion. The request is sent to administration for review and may be accepted or rejected depending on account status and associated obligations.</p><p>When approved, the account may be disabled using soft deletion rather than immediately and permanently removing every related record. This means normal account use stops while some data may be retained for restoration, financial records, protection of rights, or legal compliance.</p>',
                'sort_order' => 13,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'rights',
                'title_ar' => 'حقوقك',
                'title_en' => 'Your Rights',
                'subtitle_ar' => 'الحقوق التي قد تتاح لك بخصوص بياناتك بحسب القانون والظروف.',
                'subtitle_en' => 'Rights that may apply to your personal data depending on law and circumstances.',
                'details_ar' => '<p>بحسب القانون المعمول به وظروف كل طلب، قد يكون لك الحق في:</p><ul><li>طلب معرفة البيانات الشخصية التي نحتفظ بها عنك والحصول على نسخة منها عندما يكون ذلك متاحًا قانونًا.</li><li>طلب تصحيح أو استكمال البيانات غير الدقيقة أو الناقصة.</li><li>طلب حذف أو تعطيل الحساب والبيانات في الحالات التي يسمح بها القانون.</li><li>الاعتراض على بعض أنواع المعالجة أو طلب تقييدها عندما ينطبق ذلك.</li><li>سحب موافقتك في الحالات التي نعتمد فيها على الموافقة دون التأثير على مشروعية المعالجة السابقة.</li><li>طلب نقل بعض البيانات بصيغة مناسبة عندما يقرر القانون هذا الحق وتنطبق شروطه.</li><li>تقديم شكوى لنا أو إلى الجهة المختصة بحماية البيانات إذا كنت ترى أن بياناتك عولجت بصورة غير مشروعة.</li></ul><p>قد نطلب معلومات مناسبة للتحقق من هويتك قبل تنفيذ أي طلب متعلق بالبيانات لحماية حسابك ومنع الإفصاح لشخص غير مخول.</p>',
                'details_en' => '<p>Depending on applicable law and the circumstances of each request, you may have the right to:</p><ul><li>Ask what personal data we hold about you and obtain a copy where legally available.</li><li>Request correction or completion of inaccurate or incomplete data.</li><li>Request deletion or disabling of your account and data where permitted by law.</li><li>Object to certain processing or request restriction where applicable.</li><li>Withdraw consent where processing relies on consent, without affecting the lawfulness of earlier processing.</li><li>Request portability of certain data in an appropriate format where the law provides this right and its conditions are met.</li><li>Submit a complaint to us or to the competent data protection authority if you believe your data has been processed unlawfully.</li></ul><p>We may request appropriate information to verify your identity before acting on a data request in order to protect your account and prevent disclosure to unauthorized persons.</p>',
                'sort_order' => 14,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'messages',
                'title_ar' => 'الرسائل والإشعارات',
                'title_en' => 'Messages and Notifications',
                'subtitle_ar' => 'الرسائل التشغيلية والتسويقية التي قد نرسلها عبر الهاتف أو البريد.',
                'subtitle_en' => 'Operational and marketing messages that may be sent by phone or email.',
                'details_ar' => '<p>نستخدم رقم الهاتف أو البريد الإلكتروني لإرسال رسائل تشغيلية لازمة للخدمة، مثل رموز التحقق OTP وإشعارات الحساب وتحديثات المعاملات أو الدعم عند الحاجة.</p><p>إذا أرسلنا رسائل تسويقية أو عروضًا ترويجية، فسيكون ذلك وفقًا للقواعد القانونية والتفضيلات المتاحة للمستخدم، وسنوفر وسيلة مناسبة لطلب إيقاف هذا النوع من الرسائل حيثما ينطبق.</p>',
                'details_en' => '<p>We use your phone number or email address to send operational messages needed for the service, such as OTP verification codes, account notices, transaction updates, and support communications.</p><p>If we send marketing messages or promotional offers, we will do so in accordance with applicable rules and available user preferences, and we will provide an appropriate way to opt out where applicable.</p>',
                'sort_order' => 15,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'minors',
                'title_ar' => 'القاصرون',
                'title_en' => 'Minors',
                'subtitle_ar' => 'كيفية تعاملنا مع بيانات القاصرين والأطفال.',
                'subtitle_en' => 'How we approach data relating to minors and children.',
                'details_ar' => '<p>المنصة موجهة أساسًا للأشخاص الذين لديهم الأهلية القانونية للتعامل في الخدمات العقارية، وليست مصممة لاستهداف الأطفال. إذا علمنا بأن بيانات قاصر قد جمعت بصورة غير مناسبة، يمكن لولي الأمر التواصل معنا لطلب مراجعتها واتخاذ الإجراء الملائم.</p>',
                'details_en' => '<p>The Platform is primarily intended for people with legal capacity to engage in real estate services and is not designed to target children. If we become aware that data relating to a minor was collected inappropriately, a parent or guardian may contact us to request review and appropriate action.</p>',
                'sort_order' => 16,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'third-parties',
                'title_ar' => 'الخدمات الخارجية',
                'title_en' => 'Third-Party Services',
                'subtitle_ar' => 'الروابط والخدمات التابعة لجهات خارجية وسياسات الخصوصية الخاصة بها.',
                'subtitle_en' => 'External links and services and the privacy policies that apply to them.',
                'details_ar' => '<p>قد تحتوي المنصة على روابط أو محتوى مضمّن من مواقع أو خدمات تابعة لجهات خارجية. عند الانتقال إلى تلك الخدمات، تخضع بياناتك لسياسات الخصوصية والشروط الخاصة بها. لا نتحكم في ممارسات الخصوصية لتلك الجهات، لذلك ننصح بمراجعة سياساتها قبل تقديم بيانات شخصية إليها.</p>',
                'details_en' => '<p>The Platform may contain links to, or embedded content from, third-party websites or services. When you use those services, your data is subject to their own privacy policies and terms. We do not control the privacy practices of those parties, so we recommend reviewing their policies before providing personal data.</p>',
                'sort_order' => 17,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'transfers',
                'title_ar' => 'نقل البيانات',
                'title_en' => 'Data Transfers',
                'subtitle_ar' => 'نقل البيانات خارج مصر عند الحاجة لتشغيل بعض الخدمات التقنية.',
                'subtitle_en' => 'International transfers that may occur when certain technical services are used.',
                'details_ar' => '<p>قد تكون بعض خدمات الاستضافة أو البنية التحتية أو مزودي التقنية موجودة داخل مصر أو خارجها. إذا استلزم تشغيل الخدمة نقل بيانات شخصية إلى دولة أخرى، فنتعامل مع هذا النقل وفق المتطلبات القانونية المطبقة ونتخذ التدابير المناسبة لحماية البيانات في حدود طبيعة الخدمة ومزودها.</p>',
                'details_en' => '<p>Some hosting, infrastructure, or technology providers may operate inside or outside Egypt. If providing a service requires transferring personal data to another country, we handle that transfer in accordance with applicable legal requirements and use appropriate safeguards considering the nature of the service and provider.</p>',
                'sort_order' => 18,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'updates',
                'title_ar' => 'تحديث السياسة',
                'title_en' => 'Policy Updates',
                'subtitle_ar' => 'كيفية نشر التعديلات المستقبلية على سياسة الخصوصية.',
                'subtitle_en' => 'How future changes to this Privacy Policy will be published.',
                'details_ar' => '<p>قد نقوم بتحديث هذه السياسة من وقت لآخر لتعكس تغييرات في خدمات المنصة أو أنظمتها أو المتطلبات القانونية. سيتم نشر النسخة المحدثة على الموقع مع تاريخ آخر تحديث، وقد نستخدم وسيلة إضافية للإخطار إذا كان التغيير جوهريًا.</p><p>يسري التحديث من تاريخ نشره ما لم يذكر تاريخ آخر بشكل صريح.</p>',
                'details_en' => '<p>We may update this policy from time to time to reflect changes in Platform services, systems, or legal requirements. The updated version will be published on the website with the latest update date, and we may use an additional notice method if a change is material.</p><p>An update takes effect from the date it is published unless another date is expressly stated.</p>',
                'sort_order' => 19,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'privacy-contact',
                'title_ar' => 'التواصل معنا',
                'title_en' => 'Contact Us About Privacy',
                'subtitle_ar' => 'طريقة إرسال سؤال أو شكوى أو طلب متعلق ببياناتك الشخصية.',
                'subtitle_en' => 'How to send a privacy question, complaint, or personal data request.',
                'details_ar' => '<p>إذا كان لديك سؤال أو شكوى أو طلب متعلق ببياناتك الشخصية، تواصل معنا عبر <a href="mailto:info@rightchoice-co.com">info@rightchoice-co.com</a> أو من خلال صفحة «تواصل معنا» على الموقع.</p><p>يرجى وصف طلبك بوضوح وذكر بيانات تعريف كافية للتحقق من الحساب دون إرسال كلمات المرور أو رموز OTP.</p><div class="rc-privacy-note"><strong>تنبيه أمني:</strong> لن نطلب منك إرسال كلمة المرور أو رمز OTP الكامل عبر البريد الإلكتروني أو نموذج التواصل.</div>',
                'details_en' => '<p>If you have a question, complaint, or request relating to your personal data, contact us at <a href="mailto:info@rightchoice-co.com">info@rightchoice-co.com</a> or through the Contact Us page on the website.</p><p>Please describe your request clearly and provide enough identifying information for account verification without sending passwords or OTP codes.</p><div class="rc-privacy-note"><strong>Security notice:</strong> We will not ask you to send your password or a full OTP code by email or through a contact form.</div>',
                'sort_order' => 20,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('privacy_policy_sections');
    }
};
